---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: kube-system
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: prometheus-operator
    version: 6.11.0
  values:
    ## Configuration for alertmanager
    ## ref: https://prometheus.io/docs/alerting/alertmanager/
    ##
    alertmanager:

      ## Deploy alertmanager
      ##
      enabled: true

      ## Alertmanager configuration directives
      ## ref: https://prometheus.io/docs/alerting/configuration/#configuration-file
      ##      https://prometheus.io/webtools/alerting/routing-tree-editor/
      ##
      config:
        global:
          resolve_timeout: 5m
          slack_api_url: 'https://hooks.slack.com/services/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'
        route:
          group_wait: 10s
          group_interval: 5m
          repeat_interval: 32h
          receiver: 'slack'
          routes:
          - match:
              alertname: Watchdog
            receiver: 'slack'
        receivers:
        - name: 'slack'
          slack_configs:
          - channel: '#prom-alerts'
            send_resolved: true

    ## Manages Prometheus and Alertmanager components
    ##
    prometheusOperator:
      enabled: true

      ## Deploy CRDs used by Prometheus Operator.
      ##
      createCustomResource: false
